name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
      - name: Testing binaries
        run: |
          dotnet test:
  
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restore .NET project
      run: |
        dotnet restore
    - name: Publish binaries
      run: |
        dotnet publish
