name: CI

on:
  push:
    branches:
      - master

jobs:
  setup:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Download .NET Core
        run: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - name: Install .NET Core
        run: sudo dpkg -i packages-microsoft-prod.deb
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Test binaries
        run: |
          dotnet test
  
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restore .NET project
      run: dotnet restore
    - name: Build binaries
      run: dotnet build
